version: "3.1"

networks:
  web:
    external: true

services:
  imagebrowser:
    build: .
    container_name: imagebrowser
    ports:
      - "6969:6969"
    environment:
      - SERVER_PORT=:6969
      - LOGLEVEL=debug
    labels:
      - traefik.enable=false
    networks:
      - web

